#!/usr/bin/env python3
"""Generate manifest.inc for the bingo64 release asset extractor.

Reads assets.json (US entries) and emits a C include describing every
ROM-derived file the game needs at runtime under res/:
  - plain textures (raw texel data, possibly inside MIO0 blocks)
  - skybox / cake ending blobs (tiled images + pointer table)
  - the alo-added textures that live outside assets.json (located by
    searching the ROM's decompressed segments for their pixel data)
  - a byte-exact rebuild recipe for the four sound files (generated by
    gen_sound_recipe.py, appended here)

Run from the repo root of a fully built tree (needs baserom.us.z64 and
build/us_pc/sound/* for recipe generation):
  python3 tools/bingo64_extract/gen_manifest.py <builddir> <out.inc>
"""
import json
import os
import struct
import subprocess
import sys
import zlib

ROOT = os.getcwd()

FMT_RGBA = 0
FMT_IA = 1

# ---------------------------------------------------------------------------
# Minimal PNG decoder (stdlib only) for the handful of alo-extra textures.
# Handles 8-bit RGB/RGBA/grey/grey-alpha with standard filters.

def png_decode(path):
    data = open(path, "rb").read()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", path
    pos, w, h, depth, ctype, idat = 8, 0, 0, 0, 0, b""
    while pos < len(data):
        (ln,) = struct.unpack(">I", data[pos:pos+4])
        typ = data[pos+4:pos+8]
        body = data[pos+8:pos+8+ln]
        if typ == b"IHDR":
            w, h, depth, ctype = struct.unpack(">IIBB", body[:10])
        elif typ == b"IDAT":
            idat += body
        elif typ == b"IEND":
            break
        pos += 12 + ln
    assert depth == 8, (path, depth)
    nch = {0: 1, 2: 3, 4: 2, 6: 4}[ctype]
    raw = zlib.decompress(idat)
    stride = w * nch
    out = bytearray(h * stride)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        filt = raw[p]; p += 1
        line = bytearray(raw[p:p+stride]); p += stride
        if filt == 1:
            for i in range(nch, stride):
                line[i] = (line[i] + line[i-nch]) & 0xFF
        elif filt == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif filt == 3:
            for i in range(stride):
                a = line[i-nch] if i >= nch else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xFF
        elif filt == 4:
            for i in range(stride):
                a = line[i-nch] if i >= nch else 0
                b = prev[i]
                c = prev[i-nch] if i >= nch else 0
                pp = a + b - c
                pa, pb, pc = abs(pp-a), abs(pp-b), abs(pp-c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        out[y*stride:(y+1)*stride] = line
        prev = line
    # normalize to RGBA
    rgba = bytearray(w * h * 4)
    for i in range(w * h):
        px = out[i*nch:(i+1)*nch]
        if ctype == 6: rgba[i*4:i*4+4] = px
        elif ctype == 2: rgba[i*4:i*4+3] = px; rgba[i*4+3] = 255
        elif ctype == 4: rgba[i*4] = rgba[i*4+1] = rgba[i*4+2] = px[0]; rgba[i*4+3] = px[1]
        else: rgba[i*4] = rgba[i*4+1] = rgba[i*4+2] = px[0]; rgba[i*4+3] = 255
    return w, h, bytes(rgba)

def rgba_to_raw16(rgba):
    out = bytearray()
    for i in range(0, len(rgba), 4):
        r, g, b, a = rgba[i]>>3, rgba[i+1]>>3, rgba[i+2]>>3, 1 if rgba[i+3] >= 128 else 0
        v = (r << 11) | (g << 6) | (b << 1) | a
        out += struct.pack(">H", v)
    return bytes(out)

def rgba_to_rawia16(rgba):
    out = bytearray()
    for i in range(0, len(rgba), 4):
        out.append(rgba[i])       # intensity = red channel
        out.append(rgba[i+3])
    return bytes(out)

# ---------------------------------------------------------------------------

def mio0_decode(buf):
    assert buf[:4] == b"MIO0"
    dest_size, comp_off, uncomp_off = struct.unpack(">III", buf[4:16])
    out = bytearray()
    bit_idx = comp_idx = uncomp_idx = 0
    while len(out) < dest_size:
        if buf[16 + bit_idx // 8] & (0x80 >> (bit_idx % 8)):
            out.append(buf[uncomp_off + uncomp_idx]); uncomp_idx += 1
        else:
            v0, v1 = buf[comp_off+comp_idx], buf[comp_off+comp_idx+1]
            comp_idx += 2
            length = ((v0 & 0xF0) >> 4) + 3
            idx = ((v0 & 0x0F) << 8) + v1 + 1
            for _ in range(length):
                out.append(out[-idx])
        bit_idx += 1
    return bytes(out)

def main():
    builddir = sys.argv[1] if len(sys.argv) > 1 else "build/us_pc"
    outpath = sys.argv[2] if len(sys.argv) > 2 else "tools/bingo64_extract/manifest.inc"

    assets = json.load(open("assets.json"))
    rom = open("baserom.us.z64", "rb").read()
    sha1 = open("sm64.us.sha1").read().split()[0]

    committed = set(subprocess.run(["git", "ls-files"], capture_output=True,
                                   text=True).stdout.splitlines())

    tex, sky = [], []
    blocks = {}  # mio0 offset -> decompressed bytes

    def block(off):
        if off not in blocks:
            blocks[off] = mio0_decode(rom[off:])
        return blocks[off]

    for asset, data in assets.items():
        if asset.startswith("@") or "us" not in data[-1]:
            continue
        pos = data[-1]["us"]
        size = data[-2]
        mio0 = pos[0] if len(pos) > 1 else -1
        inner = pos[-1]
        if asset.startswith("textures/skyboxes/") and asset.endswith(".png"):
            name = os.path.basename(asset)[:-4]
            sky.append((name, size, mio0, inner, 0))
        elif asset == "levels/ending/cake.png":
            sky.append(("cake", size, mio0, inner, 1))
        elif asset.endswith(".png"):
            base = os.path.basename(asset)
            fmtname = base.rsplit(".", 2)[-2]
            fmt, depth = {"rgba16": (FMT_RGBA, 16), "rgba32": (FMT_RGBA, 32),
                          "ia1": (FMT_IA, 1), "ia4": (FMT_IA, 4),
                          "ia8": (FMT_IA, 8), "ia16": (FMT_IA, 16)}[fmtname]
            w, h = data[0], data[1]
            tex.append((asset, fmt, depth, w, h, size, mio0, inner))
        # non-png assets (m64, aiff, bin) are not needed at runtime

    # --- locate the alo extras by their pixels ---------------------------
    extras = [p for p in
              ["actors/water_waves/water_waves_0.ia16.png",
               "actors/water_waves/water_waves_1.ia16.png",
               "actors/water_waves/water_waves_2.ia16.png",
               "actors/water_waves/water_waves_3.ia16.png",
               "actors/exclamation_box/vanish_cap_box_sides.rgba16.png",
               "actors/exclamation_box/wing_cap_box_sides.rgba16.png"]
              if os.path.isfile(p) and p not in committed]
    for path in extras:
        w, h, rgba = png_decode(path)
        fmtname = path.rsplit(".", 2)[-2]
        if fmtname == "ia16":
            raw, fmt, depth = rgba_to_rawia16(rgba), FMT_IA, 16
        else:
            raw, fmt, depth = rgba_to_raw16(rgba), FMT_RGBA, 16
        loc = None
        off = rom.find(raw)
        if off >= 0:
            loc = (-1, off)
        else:
            for boff in sorted({e[6] for e in tex if e[6] >= 0} | {s[2] for s in sky if s[2] >= 0}):
                inner = block(boff).find(raw)
                if inner >= 0:
                    loc = (boff, inner)
                    break
        if loc is None:
            print(f"ERROR: cannot locate {path} in ROM (len {len(raw)})", file=sys.stderr)
            sys.exit(1)
        tex.append((path, fmt, depth, w, h, len(raw), loc[0], loc[1]))
        print(f"located extra {path}: mio0={loc[0]:#x} pos={loc[1]:#x}")

    # --- sound maps -------------------------------------------------------
    # sound_data.ctl and bank_sets ship with the game (structural data from
    # committed sources); the extractor rebuilds sequences.bin and
    # sound_data.tbl from the user's ROM via these maps.
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from gen_sound_map import build_sound_maps, verify_tbl_content
    snd = build_sound_maps(rom, builddir)
    print(verify_tbl_content(rom, builddir, snd["tbl_map"], snd["tbl_len"]))
    built_tbl = open(f"{builddir}/sound/sound_data.tbl", "rb").read()
    tbl_header = built_tbl[:snd["tbl_map"][0][0]]

    # --- emit ------------------------------------------------------------
    with open(outpath, "w") as f:
        f.write("/* Generated by gen_manifest.py -- do not edit. */\n")
        f.write(f'static const char sRomSha1[] = "{sha1}";\n')
        f.write("static const struct TexEntry sTex[] = {\n")
        for (path, fmt, depth, w, h, size, mio0, inner) in sorted(tex):
            f.write(f'{{"{path}",{fmt},{depth},{w},{h},{size},{mio0}LL,{inner}}},\n')
        f.write("};\n")
        f.write("static const struct SkyEntry sSky[] = {\n")
        for (name, size, mio0, inner, cake) in sorted(sky):
            f.write(f'{{"{name}",{size},{mio0}LL,{inner},{cake}}},\n')
        f.write("};\n")
        def emit_bytes(name, data):
            f.write(f"static const unsigned char {name}[] = {{\n")
            for i in range(0, len(data), 20):
                f.write(",".join(str(b) for b in data[i:i+20]) + ",\n")
            f.write("};\n")

        def emit_map(name, entries):
            f.write(f"static const struct CopyEntry {name}[] = {{\n")
            for (dst, src, ln) in entries:
                f.write(f"{{{dst},{src},{ln}}},\n")
            f.write("};\n")

        emit_bytes("sSeqHeader", snd["seq_header"])
        emit_map("sSeqMap", snd["seq_map"])
        f.write(f"static const unsigned int sSeqLen = {snd['seq_len']};\n")
        emit_bytes("sTblHeader", tbl_header)
        emit_map("sTblMap", snd["tbl_map"])
        f.write(f"static const unsigned int sTblLen = {snd['tbl_len']};\n")
    print(f"wrote {outpath}: {len(tex)} textures, {len(sky)} sky/cake, "
          f"{len(snd['seq_map'])} sequences, {len(snd['tbl_map'])} samples")

if __name__ == "__main__":
    main()
